org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureoncommand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

mod_name=True Toggle Sprint
mod_id=truetogglesprint
mod_version=1.0.1
mod_description=Toggle Sprint mod with a keybind and a customizable HUD
mod_archives_name=TrueToggleSprint

java_version=[VERSIONED]
minecraft_version=[VERSIONED]
fabric_loader_version=0.18.6
fabric_api_version=[VERSIONED]
stonecutter_version=0.9

yacl_version=[VERSIONED]
mod_menu_version=[VERSIONED]